### ISSUE TITLE
icon "e" wieder blau/weiss

### ISSUE THREAD

**Issue by lanimusic** [elynmusic/elyn#11]
da schrieb i aber etz au, zum checke wie cool das do isch! :D

**Comment by elynmusic** [comment]
bzw grau weiss, ja?

**Comment by lanimusic** [comment]
Jeps. :)

-------- Ursprüngliche Nachricht --------
Von: elynmusic <notifications@github.com> 
Datum:  
An: elynmusic/elyn <elyn@noreply.github.com> 
Cc: lanimusic <lanimusic@hotmail.ch> 
Betreff: Re: [elyn] icon "e" wieder blau/weiss (#11) 
 
bzw grau weiss, ja?
