### ISSUE TITLE
google+ kontos

### ISSUE THREAD

**Issue by lanimusic** [elynmusic/elyn#14]
es existieren zwei google+ konten. hätte gerne nur das konto, welches mit dem richtigen youtube-kanal verknüpft ist.

diese beiden sind vernüpft, aber es ist nicht der richtige URL bei youtube:
https://plus.google.com/105732244296932597323/about
https://www.youtube.com/channel/UCY1BkTPPFwCXRLg_7Dw7mAw

diese beiden sind auch verknüpft. hier ist youtube richtig beschriftet, aber bei der google+ Seite muss man unbedingt zwei Namen eingeben (Elyn Music) = weniger schön. 
https://plus.google.com/116381733800622943330/about
https://www.youtube.com/user/elynmusic

**Comment by elynmusic** [comment]
grundsätzlich ist's glaubs so:

"persönliches" google+ konto: https://plus.google.com/116381733800622943330/about
dazu privater youtube kanal: https://www.youtube.com/user/elynmusic 

ist administrator von google+ "brands" konto (siehe: http://www.google.com/+/brands/):
google+ "brands" konto: https://plus.google.com/105732244296932597323/about
youtube kanal: https://www.youtube.com/channel/UCY1BkTPPFwCXRLg_7Dw7mAw

idealerweise, sollte man den privaten youtube kanal  vom persönlichen google+ konto umbenennen, profil da privat einstellen, dann youtube kanal vom "brands" konto auf elynmusic umbenennen.

Immer noch todo.

**Comment by lanimusic** [comment]
vielleicht kann ich das selbst machen.werde am do schauen.danke für deine hilfe!hatte überhaupt nicht mehr die übersicht und wollte nicht das falsche löschen.

Date: Mon, 19 Jan 2015 01:30:59 -0800

**Comment by elynmusic** [comment]
müssen keines löschen, ist glaubs alles in ordnung so.

**Comment by lanimusic** [comment]
![url andern youtube](https://cloud.githubusercontent.com/assets/10477818/5938169/af1ab38e-a6f8-11e4-8d33-047db91449c1.JPG)

**Comment by lanimusic** [comment]
so könnten wir es machen. 
welcher gefällt dir besser?

meinen privaten google account hab ich in eliane sutter umbenannt.
somit wurde automatisch auch https://www.youtube.com/user/elynmusic/about
umbenannt in eliane sutter.
für den moment für uns viel übersichtlicher.
